FROM ubuntu:latest
LABEL maintainer="eg.shuraev@gmail.com"
LABEL description="This file contains instructions for \
creating an image for the Ip-manager project."
RUN bash
RUN apt-get update && \
apt-get -y upgrade && \
apt-get install -y python3-pip && \
apt-get install -y python3.10-venv
RUN python3 -m venv venv
RUN /bin/bash -c "source venv/bin/activate"
RUN pip install \
        pydantic \
        tortoise-orm \
        fastapi\
        uvicorn
# ENV PIP_ROOT_USER_ACTION=ignore
WORKDIR /src/
COPY . src/createSchema.py
RUN chmod +x src/createSchema.py
CMD ["python3", "./createSchema.py"]
EXPOSE 8000


 


